drop table if exists task_user CASCADE;
drop table if exists task CASCADE;

create table task_user (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table task (id bigint generated by default as identity, description varchar(255) not null, completed boolean not null, user_fk bigint,primary key (id));

alter table task add constraint FKn740bdsc65ipiuj1719t0gk0b foreign key (user_fk) references task_user;